### ISSUE TITLE
Dealing with external svelte components

### ISSUE THREAD

**Issue by kaisermann** [sveltejs/template-webpack#4]
Since we're excluding `/node_modules/` from the `svelte-loader`, what's the best way to use external svelte components like [svelte-routing](https://github.com/EmilTholin/svelte-routing/)?

Adding a negative lookahead to the exclusion rule kinda works, but can we assume that every svelte component/package will have the `svelte` prefix?

```js
{
  test: /\.(html|svelte)$/,
  exclude: /node_modules\/(?!svelte)/,
  ...
}
```

**Comment by Rich-Harris** [comment]
I actually hit this earlier today. I just removed the `exclude` field altogether in the project I'm working on. The `svelte-` prefix assumption is probably reasonable, but I don't know if I'd consider it watertight.

**Comment by antony** [comment]
This just got me :)

Why exclude node_modules? We're entering a world now where there are a fair few third-party svelte components.

Perhaps there should be a recommendation that Svelte components generally use a .svelte suffix, since .html causes Svelte to break in Parcel bundler, too. Im assuming that Vue uses .vue so that there aren't headaches like this.

**Comment by benmccann** [comment]
Hopefully this is fixed now with https://github.com/sveltejs/template-webpack/pull/36
